# Análise Exploratória de Dados (EDA)
## Projeto: Classificação ESG por Machine Learning
**Empresa:** NorthData Consulting  
**Dataset:** Public Company ESG Ratings  
**Fonte:** https://www.kaggle.com/datasets/alistairking/public-company-esg-ratings-dataset  
**Autor:** Phelipe C. S. Cota 
**Data:** 26/05/2026  

---

### Objetivo
Realizar a análise exploratória do dataset de ratings ESG de empresas públicas,
identificando padrões, inconsistências e insights que orientarão a modelagem de
Machine Learning para classificação e gestão de risco de fornecedores.

### Estrutura do Notebook
1. Preparação do ambiente
2. Leitura da Base de Dados
3. Visão geral do dataset
4. Análise de qualidade dos dados
5. Análise univariada
6. Análise bivariada e correlações
7. Insights e conclusões

## 1. Preparação do ambiente

In [1]:
#Bibliotecas necessárias

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Configurações de exibição

pd.set_option("display.max_columns", None)   # mostra todas as colunas
pd.set_option("display.float_format", "{:.2f}".format)  #2 casas decimais

sns.set_theme(style="whitegrid", palette="muted") #gráficos com fundo branco e grade discreta, cores suaves e menos saturadas   
plt.rcParams["figure.figsize"] = (12, 5) #tamanho padrão das figuras

## 2. Leitura da Base de Dados

Os dados serão extraídos via script de ingestão (src\ingest_data.py) diretamente do Kaggle$^1$, que serão salvos em máquina local, primeiramente na pasta \data\bronze, seguindo a filosofia da arquitetura medalhão para estruturar o pipeline de dados.

$^1$Consultar a sessão **FASE I - Extraindo dos Dados** no arquivo README.md

##Integridade dos Dados (Hash MD5)

Foi incluído o hash MD5 (Message Digest 5) para gerar um código único de 32 caracteres (hexadecimal) para garantir a integridade da base de dados baixada. Este código garante rastreabilidade quanto a alterações na base de dado, caso venha a ocorrer qualquer adulteração no dado e mudanças futuras em sua forma ou erro no download, o código gerado será outro.

##Metadata

Gerado arquivo .json com as informações de nome do arquivo, diretório em máquina local, URL de origem, data de ingestão e código MD5 hash gerado, para autidotiras futuras.

>*Arquivo metadata gerado:*   
 {  
    "arquivo": "data.csv",  
    "fonte_original": "https://www.kaggle.com/datasets/alistairking/public-company-esg-ratings-dataset",  
    "data_ingestao": "2026-05-26T22:38:56.999270",  
    "md5_hash": "68848e9627b67d88c8839c9a24e70049",  
    "metodo": "Kaggle API"  
}

In [2]:
from pathlib import Path

# Caminho relativo à raiz do projeto
BRONZE_DIR = Path("..") / "data" / "bronze"
df = pd.read_csv(BRONZE_DIR / "data.csv")

print(f"Formato do dataset carregado:")
print(f"   Linhas  : {df.shape[0]:,}")
print(f"   Colunas : {df.shape[1]}")

Formato do dataset carregado:
   Linhas  : 722
   Colunas : 21

## 3. Visão geral do dataset

In [6]:
# Primeiras linhas do dataset
print("PRIMEIRAS 10 LINHAS:")
display(df.head(10))

# Tipos de dados de cada coluna
print("\nTIPOS DE DADOS POR COLUNA:")
print(df.dtypes)

PRIMEIRAS 10 LINHAS:

,ticker,name,currency,exchange,industry,logo,weburl,environment_grade,environment_level,social_grade,social_level,governance_grade,governance_level,environment_score,social_score,governance_score,total_score,last_processing_date,total_grade,total_level,cik
0,dis,Walt Disney Co,USD,"NEW YORK STOCK EXCHANGE, INC.",Media,https://static.finnhub.io/logo/ef50b4a2b263c84...,https://thewaltdisneycompany.com/,A,High,BB,Medium,BB,Medium,510,316,321,1147,19-04-2022,BBB,High,1744489
1,gm,General Motors Co,USD,"NEW YORK STOCK EXCHANGE, INC.",Automobiles,https://static.finnhub.io/logo/9253db78-80c9-1...,https://www.gm.com/,A,High,BB,Medium,B,Medium,510,303,255,1068,17-04-2022,BBB,High,1467858
2,gww,WW Grainger Inc,USD,"NEW YORK STOCK EXCHANGE, INC.",Trading Companies and Distributors,https://static.finnhub.io/logo/f153dcda-80eb-1...,https://www.grainger.com/,B,Medium,BB,Medium,B,Medium,255,385,240,880,19-04-2022,BB,Medium,277135
3,mhk,Mohawk Industries Inc,USD,"NEW YORK STOCK EXCHANGE, INC.",Consumer products,https://static.finnhub.io/logo/26868a62-80ec-1...,https://mohawkind.com/,A,High,B,Medium,BB,Medium,570,298,303,1171,18-04-2022,BBB,High,851968
4,lyv,Live Nation Entertainment Inc,USD,"NEW YORK STOCK EXCHANGE, INC.",Media,https://static.finnhub.io/logo/1cd144d2-80ec-1...,https://www.livenationentertainment.com/,BBB,High,BB,Medium,B,Medium,492,310,250,1052,18-04-2022,BBB,High,1335258
5,lvs,Las Vegas Sands Corp,USD,"NEW YORK STOCK EXCHANGE, INC.",Hotels Restaurants and Leisure,https://static.finnhub.io/logo/7256a9be-8279-1...,https://www.sands.com/,A,High,BB,Medium,BB,Medium,547,318,313,1178,18-04-2022,BBB,High,1300514
6,clx,Clorox Co,USD,"NEW YORK STOCK EXCHANGE, INC.",Consumer products,https://static.finnhub.io/logo/a67c34fe-80eb-1...,https://www.thecloroxcompany.com/,A,High,BB,Medium,BB,Medium,560,350,345,1255,16-04-2022,A,High,21076
7,aacg,ATA Creativity Global,CNY,NASDAQ NMS - GLOBAL MARKET,Diversified Consumer Services,https://static2.finnhub.io/file/publicdatany/f...,http://www.ata.net.cn,B,Medium,B,Medium,B,Medium,203,200,205,608,01-07-2022,B,Medium,1420529
8,aal,American Airlines Group Inc,USD,NASDAQ NMS - GLOBAL MARKET,Airlines,https://static2.finnhub.io/file/publicdatany/f...,https://americanairlines.gcs-web.com/,B,Medium,B,Medium,B,Medium,270,211,265,746,16-04-2022,B,Medium,6201
9,aame,Atlantic American Corp,USD,NASDAQ NMS - GLOBAL MARKET,Insurance,https://static.finnhub.io/logo/6b536b3e-826a-1...,http://www.atlam.com/,B,Medium,B,Medium,BB,Medium,220,221,300,741,16-04-2022,B,Medium,8177

TIPOS DE DADOS POR COLUNA:
ticker                    str
name                      str
currency                  str
exchange                  str
industry                  str
logo                      str
weburl                    str
environment_grade         str
environment_level         str
social_grade              str
social_level              str
governance_grade          str
governance_level          str
environment_score       int64
social_score            int64
governance_score        int64
total_score             int64
last_processing_date      str
total_grade               str
total_level               str
cik                     int64
dtype: object

### Dicionário de dados

A partir das informações levantadas, foi possível criar um pequeno **Dicionário de Dados** desta base, disponível na pasta `/docs/dicionario_de_dados.md`

### Relevâncias

Os principais dados para as ferramentas de classificação e regressão por Machine Learning, estão da coluna 9 até a 20 (**Scores numéricos** e **Notas/Níveis**), sendo que as colunas `grades` e `scores` parecem demonstrar redundância entre si, ou seja, trazem a mesma informação mas utilizando dados diferentes, sendo necessário para o modelo a ser construído, utilizar somente uma entre estas.

## 4. Análise de qualidade dos dados

Será feita uma verificação quanto a valores nulos, duplicatas e consistência geral.

In [ ]:
print("=" * 50)
print("ANÁLISE DE QUALIDADE DOS DADOS")
print("=" * 50)

# Valores nulos
nulos = df.isnull().sum()
pct_nulos = (nulos / len(df) * 100).round(2)

qualidade = pd.DataFrame({
    "Nulos"      : nulos,
    "% Nulos"    : pct_nulos,
    "Tipo"       : df.dtypes
}).sort_values("% Nulos", ascending=False)

print("\nVALORES NULOS POR COLUNA:")
display(qualidade)

# Duplicatas
duplicatas = df.duplicated().sum()
print(f"\nLINHAS DUPLICADAS: {duplicatas}")

# Período dos dados - Apenas leitura, ignorando conversão a ser feita na camada silver
data_min = pd.to_datetime(df["last_processing_date"], format="%d-%m-%Y").min()
data_max = pd.to_datetime(df["last_processing_date"], format="%d-%m-%Y").max()
intervalo = (data_max - data_min).days

print(f"\n PERÍODO DOS DADOS:")
print(f"   Data mais antiga : {data_min.strftime('%d/%m/%Y')}")
print(f"   Data mais recente: {data_max.strftime('%d/%m/%Y')}")
print(f"   Intervalo total  : {intervalo} dias")

==================================================
ANÁLISE DE QUALIDADE DOS DADOS
==================================================

VALORES NULOS POR COLUNA:

                      Nulos  % Nulos   Tipo
logo                     20     2.77    str
weburl                   16     2.22    str
industry                 13     1.80    str
ticker                    0     0.00    str
name                      0     0.00    str
exchange                  0     0.00    str
currency                  0     0.00    str
environment_grade         0     0.00    str
environment_level         0     0.00    str
social_grade              0     0.00    str
social_level              0     0.00    str
governance_grade          0     0.00    str
governance_level          0     0.00    str
environment_score         0     0.00  int64
social_score              0     0.00  int64
governance_score          0     0.00  int64
total_score               0     0.00  int64
last_processing_date      0     0.00    str
total_grade               0     0.00    str
total_level               0     0.00    str
cik                       0     0.00  int64

LINHAS DUPLICADAS: 0

📅 PERÍODO DOS DADOS:
   Data mais antiga : 16/04/2022
   Data mais recente: 15/11/2022
   Intervalo total  : 213 dias

### Conclusões sobre a qualidade dos dados

O data set aparenta ser de boa qualidade, com ***zero duplicatas*** (o que causaria batante ruído ao executar o treinamento do algoritmo), com ausência de ***zeros ou nulos*** nas colunas de `score` e `grade` (o que representaria perda de informação relevante para as análises). Havendo nulos apenas as colunas `logo`, `weburl` e `industry`, onde haveria apenas uma perda de informação para `industry`, pois esta coluna terá utilidade para encontrar correlações, porém, ainda com um valor baixo, de 1,8% de valores nulos para esta coluna.

Todos os dados foram registrados dentro do mesmo ano, ***de abril a novembro de 2022***, havendo assim, menor possibilidade distorção na comparação entre empresas por fatores ligados a temporalidade, principalmente por considerar-se a relevância de que cada ano fiscal tem para os resultados divulgados pelas organizações.

### Anotações prévias para a transformação para a camada Silver

[ ] logo     → descartar coluna
[ ] weburl   → descartar coluna
[ ] industry → tratar 13 nulos (imputar "Unknown" ou excluir registros)
[ ] last_processing_date → converter para datetime (formato %d-%m-%Y)

#Estatísticas Descritivas

#Tratamento dos Dados